#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Oct 06 10:49:54 MDT 2026
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim SevenSegmentTest_behav -key {Behavioral:sim_1:Functional:SevenSegmentTest} -tclbatch SevenSegmentTest.tcl -log simulate.log"
xsim SevenSegmentTest_behav -key {Behavioral:sim_1:Functional:SevenSegmentTest} -tclbatch SevenSegmentTest.tcl -log simulate.log

