set_property SRC_FILE_INFO {cfile:/home/a02447865/Downloads/Basys3Master.xdc rfile:../../../../../../Downloads/Basys3Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clkin]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {clkout}]
